---
datasource:
  schema:
    type: jsonSchema
    props:
      type: object
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: array
        spec:
          type: object
          properties:
            network:
              type: object
              properties:
                ip:
                  type: string

fields:
  - component: schema-field
    props:
      source: schema
      name: metadata.name

  - component: schema-field
    props:
      source: schema
      name: metadata.labels

  - component: schema-field
    props:
      source: schema
      name: spec.network.ip
